### ISSUE TITLE
html5ever v0.16.0 contains breaking changes

### ISSUE THREAD

**Issue by mischov** [hansihe/html5ever_elixir#5]
html5ever v0.16.0 changes a bunch of things and will probably break the nif, so you may want to lock down the html5ever version in your Cargo.toml until you fix things.

**Comment by hansihe** [comment]
I updated to the new html5ever version, made the version requirements more strict, and published a new version.

**Comment by hansihe** [comment]
@mischov Just to bring it up, I added something similar to what your fork provides.

You can see how it looks like [here](https://github.com/hansihe/html5ever_elixir/blob/master/test/html5ever_test.exs#L17-L25).

Would you be able to use this? What changes would need to be made for you to use it?

**Comment by mischov** [comment]
It's pretty close to what I would need, but not close enough. The big differences are:

  1. Maps instead of structs, and I make a lot of use of struct matching / dispatch. To use maps would require some substantial rewrites and I'm not sure if it would be a good change.
  2. I split namespace prefix from element tag.
  3. I separate text nodes whose parents are style or script tags as a different type (data, not text), which isn't particularly HTML5 accurate but which makes extracting easier later.
  4. I don't make document the root node, but maybe I should.
  5. I don't handle processing instructions, but probably I should.

I could translate what you have into what I need but it would add back the cost of walking the whole document again on Elixir-side and producing a new document.

**Comment by hansihe** [comment]
I would like to resolve these issues the best I can, but I want to keep this NIF as generic as possible.

1. Would it help if I defined structs and used them instead?
2. I definitely planned this, what I have currently is just a rough initial implementation.
3. How difficult would it be for you to do without this? I would prefer to keep the output DOM as close to the original as possible. I don't quite like the thought of this change.
4. I like having a node type for document because it makes things a bit more consistent. You only have a single root node, which have several children. The document node type is also used for document fragments, which are in html template tags.
5. They are not really important, but I try to handle them for completeness.

I guess the question I should ask is, if we manage to adequately solve the issues you currently have with this implementation, would you want to go over to using it? Or would you rather prefer to maintain your own fork?

**Comment by mischov** [comment]
1. The most useful thing would be if you allowed me to define the struct key or had some mechanism I could hook into to NIFEncode how I wanted. I define a behaviour on my structs so I would prefer to use them. The flat-dom itself is basically what I create, I just want to encode differently.
3. It would make filtering style and script data out of other text much more expensive because I would need to check the parent type of the text nodes. Not a deal breaker, though.
4. I don't disagree and having the document node as root would have made my life easier when I was implementing XPath selectors.
5. I need processing instructions to support some of XPath better anyway.
